version: '3.8'

services:
  app-backend:
    image: parthsujalshah/djangoblog:backend-app
    build:
      context: .
      dockerfile: Docker/backend/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000

  nginx-proxy:
    image: parthsujalshah/djangoblog:proxy-nginx
    build:
        context: .
        dockerfile: Docker/nginx/Dockerfile
    ports:
      - 8081:80
    depends_on:
      - app-backend