version: '3.8'

services:
  app-backend:
    build:
      context: .
      dockerfile: Docker/backend/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env

  nginx-proxy:
    build:
      context: .
      dockerfile: Docker/nginx/Dockerfile
    ports:
      - 8081:80
    depends_on:
      - backend